//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalitikBilisimSite.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalitikBilisimSite.UI.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANASAYFA.
        /// </summary>
        internal static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇÖZÜMLERİMİZ.
        /// </summary>
        internal static string ÇözümBaşlık {
            get {
                return ResourceManager.GetString("ÇözümBaşlık", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇÖZÜMLERİMİZ.
        /// </summary>
        internal static string Çözümlerimiz {
            get {
                return ResourceManager.GetString("Çözümlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masanın balıkhaneye dergi koşuyorlar eve doğru bilgiyasayarı gidecekmiş lakin öyle ki gördüm gördüm de ve çünkü. Umut göze çarpan gitti koşuyorlar gidecekmiş ekşili çorba. Çobanın gördüm eve doğru anlamsız bahar. Göze çarpan masanın batarya kutusu ekşili çorba patlıcan sarmal açılmadan dolayı bilgiyasayarı göze çarpan cezbelendi ekşili çorba. Bahar de dergi öyle ki gitti balıkhaneye hesap makinesi batarya kutusu şafak mutlu oldular. Kapının kulu otobüs domates lambadaki otobüs ve ötekinden dolayı gazete bat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ÇözümYazı {
            get {
                return ResourceManager.GetString("ÇözümYazı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazla.
        /// </summary>
        internal static string DahaFazla {
            get {
                return ResourceManager.GetString("DahaFazla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Bülteni.
        /// </summary>
        internal static string FooterHaber {
            get {
                return ResourceManager.GetString("FooterHaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analitik Bilişim(AB), 2009 yılında uzun yıllar bilişim sektöründe tecrübe kazanmış deneyimli kadrosuyla kurulmuştur. Yılların getirdiği deneyimimizi MS Dynamics Ax&apos;a entegre ederek hızlı, düşük maliyetli, etkin ve yüksek standartlarda çözümler üretiyoruz..
        /// </summary>
        internal static string FooterYazı {
            get {
                return ResourceManager.GetString("FooterYazı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HABERLER.
        /// </summary>
        internal static string HaberBaşlık {
            get {
                return ResourceManager.GetString("HaberBaşlık", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HABERLER.
        /// </summary>
        internal static string Haberler {
            get {
                return ResourceManager.GetString("Haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKIMIZDA.
        /// </summary>
        internal static string Hakkımızda {
            get {
                return ResourceManager.GetString("Hakkımızda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIZMETLERİMIZ.
        /// </summary>
        internal static string HizmetBaşlık {
            get {
                return ResourceManager.GetString("HizmetBaşlık", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HİZMETLERİMİZ.
        /// </summary>
        internal static string Hizmetlerimiz {
            get {
                return ResourceManager.GetString("Hizmetlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masanın balıkhaneye dergi koşuyorlar eve doğru bilgiyasayarı gidecekmiş lakin öyle ki gördüm gördüm de ve çünkü. Umut göze çarpan gitti koşuyorlar gidecekmiş ekşili çorba. Çobanın gördüm eve doğru anlamsız bahar. Göze çarpan masanın batarya kutusu ekşili çorba patlıcan sarmal açılmadan dolayı bilgiyasayarı göze çarpan cezbelendi ekşili çorba. Bahar de dergi öyle ki gitti balıkhaneye hesap makinesi batarya kutusu şafak mutlu oldular. Kapının kulu otobüs domates lambadaki otobüs ve ötekinden dolayı gazete bat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HizmetYazı {
            get {
                return ResourceManager.GetString("HizmetYazı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM.
        /// </summary>
        internal static string İletişim {
            get {
                return ResourceManager.GetString("İletişim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİZE ULAŞIN.
        /// </summary>
        internal static string İletişimPage {
            get {
                return ResourceManager.GetString("İletişimPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string İsim {
            get {
                return ResourceManager.GetString("İsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        internal static string Konu {
            get {
                return ResourceManager.GetString("Konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        internal static string Mesaj {
            get {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Gönder.
        /// </summary>
        internal static string MesajGonder {
            get {
                return ResourceManager.GetString("MesajGonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERANSLAR.
        /// </summary>
        internal static string ReferansBaşlık {
            get {
                return ResourceManager.GetString("ReferansBaşlık", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERANSLAR.
        /// </summary>
        internal static string Referanslar {
            get {
                return ResourceManager.GetString("Referanslar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
    }
}
